export const handleKey = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "space",
  "backspace",
  "enter",
  "ctrl+v"
];

export const example =
  "La nuit dans Paris Sud, je pense en grand \n Sais-tu ce que ça coûte de vivre ? \nQuand les gens s'endorment à travers la vitre \nJe vois les feux ensanglanter les gouttes de pluie, et je pense \nRien ne peut m'arriver, j'ai le cœur ensommeillé \nMais cette nuit j'ai mal rêvé, la douleur m'a réveillé \nFaire le Pont de la Concorde et revenir à pied \nEt t'aimer au-delà d'ton corps, yeah \nPenses-tu qu'un jour on ira mieux ?\nJe rêvais d'avenir radieux, vu qu'on pensait finir à deux\nMais tire un trait, t'as tout raté\nT'inquiète avant de dire adieu j'ai des prières à dire à Dieu\nJe me tairai une fois enterré mais la Terre est irradiée\n";
