export const myDic = {
	a: [ 'é', 'è' ],
	æ: [ 'é' ],
	aî: [ 'é', 'è' ],
	aie: [ 'é', 'è' ],
	ay: [ 'é', 'è' ],
	e: [ 'é', 'è' ],
	é: [ 'é' ],
	ê: [ 'é', 'è' ],
	ë: [ 'é', 'è' ],
	ea: [ 'é', 'è' ],
	ed: [ 'é' ],
	eds: [ 'é' ],
	ee: [ 'é', 'è' ],
	ée: [ 'é' ],
	éent: [ 'é' ],
	ées: [ 'é' ],
	ees: [ 'é' ],
	ef: [ 'é', 'è' ],
	efs: [ 'é', 'è' ],
	eh: [ 'é', 'è' ],
	èh: [ 'é', 'è' ],
	ehe: [ 'é' ],
	ehes: [ 'é' ],
	ehs: [ 'é' ],
	èhs: [ 'é' ],
	ei: [ 'é', 'è' ],
	ept: [ 'é' ],
	er: [ 'é' ],
	ers: [ 'é' ],
	ës: [ 'é' ],
	és: [ 'é' ],
	es: [ 'é', 'è' ],
	et: [ 'é', 'è' ],
	ez: [ 'é', 'è' ],
	ha: [ 'é' ],
	hai: [ 'é', 'è' ],
	he: [ 'é', 'è' ],
	hé: [ 'é' ],
	ier: [ 'é' ],
	iers: [ 'é' ],
	œ: [ 'é', 'è' ],
	ä: [ 'è' ],
	ai: [ 'è' ],
	aid: [ 'è' ],
	aids: [ 'è' ],
	aient: [ 'è' ],
	aies: [ 'è' ],
	ais: [ 'è' ],
	ait: [ 'è' ],
	aît: [ 'è' ],
	aits: [ 'è' ],
	aix: [ 'è' ],
	aye: [ 'è' ],
	ayes: [ 'è' ],
	ays: [ 'è' ],
	è: [ 'è' ],
	ect: [ 'è' ],
	ects: [ 'è' ],
	egs: [ 'è' ],
	eî: [ 'è' ],
	ès: [ 'è' ],
	est: [ 'è' ],
	êt: [ 'è' ],
	ets: [ 'è' ],
	êts: [ 'è' ],
	ey: [ 'è' ],
	eys: [ 'è' ],
	haie: [ 'è' ],
	haies: [ 'è' ],
	hais: [ 'è' ],
	hait: [ 'è' ],
	haits: [ 'è' ],
	hè: [ 'è' ],
	hê: [ 'è' ],
	hea: [ 'è' ],
	hee: [ 'è' ],
	hei: [ 'è' ],
	e: [ 'i', 'é', 'è', 'a', 'eu', 'an' ],
	ea: [ 'i', 'é', 'è' ],
	ee: [ 'i', 'é', 'è' ],
	ees: [ 'i', 'é' ],
	eo: [ 'i', 'o' ],
	hi: [ 'i' ],
	hî: [ 'i' ],
	hie: [ 'i' ],
	hies: [ 'i' ],
	his: [ 'i' ],
	hit: [ 'i' ],
	hît: [ 'i' ],
	hy: [ 'i' ],
	i: [ 'i', 'a', 'eu' ],
	î: [ 'i', 'a' ],
	ï: [ 'i' ],
	ict: [ 'i' ],
	icts: [ 'i' ],
	id: [ 'i', 'a' ],
	ids: [ 'i', 'a' ],
	ïe: [ 'i' ],
	ie: [ 'i', 'a' ],
	ient: [ 'i', 'a' ],
	ies: [ 'i', 'a' ],
	ïes: [ 'i' ],
	ih: [ 'i' ],
	ii: [ 'i' ],
	il: [ 'i' ],
	ils: [ 'i' ],
	ïs: [ 'i' ],
	is: [ 'i', 'a' ],
	ît: [ 'i', 'a' ],
	ït: [ 'i' ],
	it: [ 'i', 'a' ],
	its: [ 'i', 'a' ],
	ix: [ 'i', 'a' ],
	iz: [ 'i' ],
	u: [ 'i', 'a', 'o', 'ou', 'u', 'eu' ],
	y: [ 'i', 'a' ],
	ye: [ 'i', 'a' ],
	yes: [ 'i', 'a' ],
	yg: [ 'i' ],
	a: [ 'é', 'è', 'a', 'o', 'eu' ],
	æ: [ 'é' ],
	aî: [ 'é', 'è' ],
	aie: [ 'é', 'è' ],
	ay: [ 'é', 'è' ],
	é: [ 'é' ],
	ê: [ 'é', 'è', 'a' ],
	ë: [ 'é', 'è' ],
	ed: [ 'é' ],
	eds: [ 'é' ],
	ée: [ 'é' ],
	éent: [ 'é' ],
	ées: [ 'é' ],
	ef: [ 'é', 'è' ],
	efs: [ 'é', 'è' ],
	eh: [ 'é', 'è' ],
	èh: [ 'é', 'è' ],
	ehe: [ 'é' ],
	ehes: [ 'é' ],
	ehs: [ 'é' ],
	èhs: [ 'é' ],
	ei: [ 'é', 'è' ],
	ept: [ 'é' ],
	er: [ 'é' ],
	ers: [ 'é' ],
	ës: [ 'é' ],
	és: [ 'é' ],
	es: [ 'é', 'è', 'eu' ],
	et: [ 'é', 'è' ],
	ez: [ 'é', 'è' ],
	ha: [ 'é', 'a', 'o' ],
	hai: [ 'é', 'è' ],
	he: [ 'é', 'è', 'a', 'eu' ],
	hé: [ 'é' ],
	ier: [ 'é' ],
	iers: [ 'é' ],
	œ: [ 'é', 'è', 'eu' ],
	ä: [ 'è' ],
	ai: [ 'è', 'eu' ],
	aid: [ 'è' ],
	aids: [ 'è' ],
	aient: [ 'è' ],
	aies: [ 'è' ],
	ais: [ 'è' ],
	ait: [ 'è' ],
	aît: [ 'è' ],
	aits: [ 'è' ],
	aix: [ 'è' ],
	aye: [ 'è' ],
	ayes: [ 'è' ],
	ays: [ 'è' ],
	è: [ 'è' ],
	ect: [ 'è' ],
	ects: [ 'è' ],
	egs: [ 'è' ],
	eî: [ 'è' ],
	ès: [ 'è' ],
	est: [ 'è' ],
	êt: [ 'è' ],
	ets: [ 'è' ],
	êts: [ 'è' ],
	ey: [ 'è' ],
	eys: [ 'è' ],
	haie: [ 'è' ],
	haies: [ 'è' ],
	hais: [ 'è' ],
	hait: [ 'è' ],
	haits: [ 'è' ],
	hè: [ 'è' ],
	hê: [ 'è' ],
	hea: [ 'è' ],
	hee: [ 'è' ],
	hei: [ 'è' ],
	à: [ 'a' ],
	ac: [ 'a' ],
	ach: [ 'a', 'o' ],
	achs: [ 'a' ],
	acs: [ 'a' ],
	ae: [ 'a' ],
	ah: [ 'a' ],
	ahs: [ 'a' ],
	ao: [ 'a', 'o' ],
	ap: [ 'a' ],
	aps: [ 'a' ],
	as: [ 'a' ],
	at: [ 'a' ],
	ats: [ 'a' ],
	has: [ 'a' ],
	ig: [ 'a' ],
	igt: [ 'a' ],
	igts: [ 'a' ],
	îts: [ 'a' ],
	o: [ 'a', 'o', 'ou', 'eu' ],
	ys: [ 'a' ],
	â: [ 'a' ],
	aa: [ 'a' ],
	ars: [ 'a' ],
	ât: [ 'a' ],
	âts: [ 'a' ],
	az: [ 'a' ],
	hâ: [ 'a' ],
	al: [ 'o' ],
	au: [ 'o' ],
	aw: [ 'o' ],
	hau: [ 'o' ],
	ho: [ 'o' ],
	hô: [ 'o' ],
	oa: [ 'o' ],
	oe: [ 'o' ],
	oen: [ 'o' ],
	oho: [ 'o' ],
	oo: [ 'o', 'ou' ],
	ow: [ 'o', 'ou' ],
	ü: [ 'o', 'u' ],
	aos: [ 'o' ],
	aud: [ 'o' ],
	auds: [ 'o' ],
	aul: [ 'o' ],
	ault: [ 'o' ],
	aults: [ 'o' ],
	aulx: [ 'o' ],
	aus: [ 'o' ],
	aut: [ 'o' ],
	auts: [ 'o' ],
	aux: [ 'o' ],
	eau: [ 'o' ],
	eaux: [ 'o' ],
	haut: [ 'o' ],
	hauts: [ 'o' ],
	haw: [ 'o' ],
	heau: [ 'o' ],
	hot: [ 'o' ],
	hots: [ 'o' ],
	ô: [ 'o' ],
	oc: [ 'o' ],
	ocs: [ 'o' ],
	ods: [ 'o' ],
	oh: [ 'o' ],
	op: [ 'o' ],
	ops: [ 'o' ],
	os: [ 'o' ],
	ot: [ 'o' ],
	ôt: [ 'o' ],
	oth: [ 'o' ],
	oths: [ 'o' ],
	ôts: [ 'o' ],
	ots: [ 'o' ],
	ows: [ 'o' ],
	aou: [ 'ou' ],
	aoul: [ 'ou' ],
	aouls: [ 'ou' ],
	août: [ 'ou' ],
	aoûts: [ 'ou' ],
	ew: [ 'ou' ],
	ewe: [ 'ou' ],
	ewent: [ 'ou' ],
	ewes: [ 'ou' ],
	ews: [ 'ou' ],
	hoo: [ 'ou' ],
	hou: [ 'ou' ],
	houe: [ 'ou' ],
	houes: [ 'ou' ],
	hout: [ 'ou' ],
	houts: [ 'ou' ],
	houx: [ 'ou' ],
	ou: [ 'ou', 'eu' ],
	où: [ 'ou' ],
	oû: [ 'ou' ],
	oub: [ 'ou' ],
	oubs: [ 'ou' ],
	ouc: [ 'ou' ],
	oucs: [ 'ou' ],
	oud: [ 'ou' ],
	ouds: [ 'ou' ],
	oue: [ 'ou' ],
	ouent: [ 'ou' ],
	oues: [ 'ou' ],
	oug: [ 'ou' ],
	ougs: [ 'ou' ],
	ouh: [ 'ou' ],
	oûl: [ 'ou' ],
	ouls: [ 'ou' ],
	oûls: [ 'ou' ],
	oult: [ 'ou' ],
	oup: [ 'ou' ],
	oups: [ 'ou' ],
	ous: [ 'ou' ],
	oût: [ 'ou' ],
	out: [ 'ou' ],
	outs: [ 'ou' ],
	oûts: [ 'ou' ],
	oux: [ 'ou' ],
	û: [ 'ou', 'u' ],
	ue: [ 'ou', 'u' ],
	us: [ 'ou', 'u' ],
	uu: [ 'ou' ],
	eu: [ 'u', 'eu' ],
	eû: [ 'u', 'eu' ],
	eue: [ 'u', 'eu' ],
	eues: [ 'u', 'eu' ],
	eus: [ 'u', 'eu' ],
	eut: [ 'u', 'eu' ],
	eût: [ 'u' ],
	hu: [ 'u', 'eu' ],
	hue: [ 'u' ],
	huent: [ 'u' ],
	hues: [ 'u' ],
	hus: [ 'u' ],
	hut: [ 'u' ],
	huts: [ 'u' ],
	ud: [ 'u' ],
	uds: [ 'u' ],
	uë: [ 'u' ],
	üh: [ 'u' ],
	uent: [ 'u' ],
	uës: [ 'u' ],
	ues: [ 'u' ],
	uh: [ 'u' ],
	ui: [ 'u' ],
	ul: [ 'u' ],
	uls: [ 'u' ],
	ut: [ 'u' ],
	ût: [ 'u' ],
	uth: [ 'u' ],
	uths: [ 'u' ],
	uts: [ 'u' ],
	ûts: [ 'u' ],
	ux: [ 'u' ],
	euf: [ 'eu' ],
	euh: [ 'eu' ],
	euhs: [ 'eu' ],
	eur: [ 'eu' ],
	eurs: [ 'eu' ],
	eux: [ 'eu' ],
	heu: [ 'eu' ],
	ö: [ 'eu' ],
	oeh: [ 'eu' ],
	œu: [ 'eu' ],
	œud: [ 'eu' ],
	œuds: [ 'eu' ],
	œufs: [ 'eu' ],
	œux: [ 'eu' ],
	on: [ 'eu', 'on' ],
	ent: [ 'eu', 'in', 'an' ],
	aim: [ 'in' ],
	aims: [ 'in' ],
	ain: [ 'in' ],
	ainc: [ 'in' ],
	aincs: [ 'in' ],
	aing: [ 'in' ],
	aings: [ 'in' ],
	ains: [ 'in' ],
	aint: [ 'in' ],
	aints: [ 'in' ],
	ein: [ 'in' ],
	eing: [ 'in' ],
	eings: [ 'in' ],
	eins: [ 'in' ],
	eint: [ 'in' ],
	eints: [ 'in' ],
	en: [ 'in', 'an' ],
	ens: [ 'in', 'an' ],
	hein: [ 'in' ],
	hen: [ 'in', 'an' ],
	hin: [ 'in' ],
	im: [ 'in' ],
	in: [ 'in' ],
	în: [ 'in' ],
	ïn: [ 'in' ],
	inc: [ 'in' ],
	inct: [ 'in' ],
	incts: [ 'in' ],
	ing: [ 'in' ],
	ings: [ 'in' ],
	ingt: [ 'in' ],
	ingts: [ 'in' ],
	ins: [ 'in' ],
	int: [ 'in' ],
	înt: [ 'in' ],
	ints: [ 'in' ],
	ym: [ 'in' ],
	yms: [ 'in' ],
	yn: [ 'in' ],
	eun: [ 'in' ],
	hum: [ 'in' ],
	um: [ 'in' ],
	ums: [ 'in' ],
	un: [ 'in' ],
	uns: [ 'in' ],
	unt: [ 'in' ],
	unts: [ 'in' ],
	aans: [ 'an' ],
	am: [ 'an' ],
	amp: [ 'an' ],
	amps: [ 'an' ],
	ams: [ 'an' ],
	an: [ 'an' ],
	anc: [ 'an' ],
	ancs: [ 'an' ],
	and: [ 'an' ],
	ands: [ 'an' ],
	ang: [ 'an' ],
	angs: [ 'an' ],
	ans: [ 'an' ],
	ant: [ 'an' ],
	ants: [ 'an' ],
	ão: [ 'an' ],
	aon: [ 'an' ],
	aons: [ 'an' ],
	ãos: [ 'an' ],
	em: [ 'an' ],
	emp: [ 'an' ],
	emps: [ 'an' ],
	empt: [ 'an' ],
	empts: [ 'an' ],
	end: [ 'an' ],
	ends: [ 'an' ],
	eng: [ 'an' ],
	engs: [ 'an' ],
	ents: [ 'an' ],
	ham: [ 'an' ],
	han: [ 'an' ],
	hans: [ 'an' ],
	hon: [ 'on' ],
	om: [ 'on' ],
	omb: [ 'on' ],
	ombs: [ 'on' ],
	omp: [ 'on' ],
	omps: [ 'on' ],
	ompt: [ 'on' ],
	ompts: [ 'on' ],
	oms: [ 'on' ],
	onc: [ 'on' ],
	ond: [ 'on' ],
	onds: [ 'on' ],
	ong: [ 'on' ],
	ongs: [ 'on' ],
	ons: [ 'on' ],
	ont: [ 'on' ],
	onts: [ 'on' ]
};
